import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Recipes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Home</h2>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sapiente, quod dignissimos non
        iste doloribus exercitationem earum omnis natus nostrum quasi, dicta accusantium aliquam
        enim officia velit nihil quam sit doloremque!
      </p>
    </div>
  );
}
